window.SUNEUM_DATA = window.SUNEUM_DATA || {};

const DAEGU_MP_VERIFICATION = "https://img.nec.go.kr/cmm/dozen/view.do?bcIdx=233924&cbIdx=1129&fileNo=1";
const DAEGU_MP_PARTY_SOURCE = "https://www.peoplepowerparty.kr/about/people_partisan?sido=%EB%8C%80%EA%B5%AC";

window.SUNEUM_DATA.people = [
  { id: "PER-MP-DG-JUNG-NAM", name: "김기웅", type: "국회의원", position: "제22대 국회의원", district: "대구 중구·남구", constituencyId: "CON-DAEGU-JUNG-NAM", regionIds: ["DAEGU-JUNG", "DAEGU-NAM"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["김기웅 의원", "대구 중구남구 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-DONG-GUNWI-A", name: "최은석", type: "국회의원", position: "제22대 국회의원", district: "대구 동구·군위군 갑", constituencyId: "CON-DAEGU-DONG-GUNWI-A", regionIds: ["DAEGU-DONG", "DAEGU-GUNWI"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["최은석 의원", "대구 동구군위군갑 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-DONG-GUNWI-B", name: "강대식", type: "국회의원", position: "제22대 국회의원", district: "대구 동구·군위군 을", constituencyId: "CON-DAEGU-DONG-GUNWI-B", regionIds: ["DAEGU-DONG", "DAEGU-GUNWI"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["강대식 의원", "대구 동구군위군을 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-SEO", name: "김상훈", type: "국회의원", position: "제22대 국회의원", district: "대구 서구", constituencyId: "CON-DAEGU-SEO", regionIds: ["DAEGU-SEO"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["김상훈 의원", "대구 서구 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-BUK-A", name: "우재준", type: "국회의원", position: "제22대 국회의원", district: "대구 북구 갑", constituencyId: "CON-DAEGU-BUK-A", regionIds: ["DAEGU-BUK"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["우재준 의원", "대구 북구갑 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-BUK-B", name: "김승수", type: "국회의원", position: "제22대 국회의원", district: "대구 북구 을", constituencyId: "CON-DAEGU-BUK-B", regionIds: ["DAEGU-BUK"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["김승수 의원", "대구 북구을 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-SUSEONG-A", name: "주호영", type: "국회의원", position: "제22대 국회의원", district: "대구 수성구 갑", constituencyId: "CON-DAEGU-SUSEONG-A", regionIds: ["DAEGU-SUSEONG"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["주호영 의원", "대구 수성구갑 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-SUSEONG-B", name: "이인선", type: "국회의원", position: "제22대 국회의원", district: "대구 수성구 을", constituencyId: "CON-DAEGU-SUSEONG-B", regionIds: ["DAEGU-SUSEONG"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["이인선 의원", "대구 수성구을 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-DALSEO-A", name: "유영하", type: "국회의원", position: "제22대 국회의원", district: "대구 달서구 갑", constituencyId: "CON-DAEGU-DALSEO-A", regionIds: ["DAEGU-DALSEO"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["유영하 의원", "대구 달서구갑 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-DALSEO-B", name: "윤재옥", type: "국회의원", position: "제22대 국회의원", district: "대구 달서구 을", constituencyId: "CON-DAEGU-DALSEO-B", regionIds: ["DAEGU-DALSEO"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["윤재옥 의원", "대구 달서구을 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-DALSEO-C", name: "권영진", type: "국회의원", position: "제22대 국회의원", district: "대구 달서구 병", constituencyId: "CON-DAEGU-DALSEO-C", regionIds: ["DAEGU-DALSEO"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["권영진 의원", "대구 달서구병 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },
  { id: "PER-MP-DG-DALSEONG", name: "추경호", type: "국회의원", position: "제22대 국회의원", district: "대구 달성군", constituencyId: "CON-DAEGU-DALSEONG", regionIds: ["DAEGU-DALSEONG"], affiliation: "국민의힘", term: "2024.05.30.~2028.05.29.", aliases: ["추경호 의원", "대구 달성군 국회의원"], homepage: "", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "verified_registry", verificationStatus: "공식명부확인", verificationSource: DAEGU_MP_VERIFICATION, affiliationSource: DAEGU_MP_PARTY_SOURCE, lastVerified: "2026-09-02" },

  { id: "PER-MP-001", name: "예시-대구국회의원", type: "국회의원", position: "국회의원(예시)", district: "대구 중구·남구(예시자료)", regionIds: ["DAEGU-JUNG", "DAEGU-NAM"], affiliation: "가상정당 가(예시)", term: "2024.05.30.~2028.05.29.", aliases: ["예시-대구국회의원"], homepage: "https://example.com/mp", blog: "https://example.com/mp/blog", youtube: "https://example.com/mp/youtube", facebook: "", instagram: "https://example.com/mp/instagram", threads: "", otherSns: "", active: true, focusDefault: true, recordKind: "sample", verificationStatus: "예시데이터", verificationSource: "", lastVerified: "2026-09-02" },
  { id: "PER-MAYOR-001", name: "예시-대구구청장", type: "지방자치단체장", position: "구청장(예시)", district: "대구 동구(예시자료)", regionIds: ["DAEGU-DONG"], affiliation: "가상정당 가(예시)", term: "2026.07.01.~2030.06.30.", aliases: ["예시-대구구청장"], homepage: "https://example.com/mayor", blog: "", youtube: "https://example.com/mayor/youtube", facebook: "", instagram: "https://example.com/mayor/instagram", threads: "", otherSns: "", active: true, focusDefault: true, recordKind: "sample", verificationStatus: "예시데이터", verificationSource: "", lastVerified: "2026-09-01" },
  { id: "PER-CITY-001", name: "예시-대구시의원", type: "시·도의원", position: "대구광역시의원(예시)", district: "대구 북구 제1선거구(예시자료)", regionIds: ["DAEGU-BUK"], affiliation: "가상정당 가(예시)", term: "2026.07.01.~2030.06.30.", aliases: ["예시-대구시의원"], homepage: "https://example.com/city1", blog: "https://example.com/city1/blog", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "sample", verificationStatus: "예시데이터", verificationSource: "", lastVerified: "2026-08-31" },
  { id: "PER-LOCAL-001", name: "예시-대구구의원1", type: "구·시·군의원", position: "구의원(예시)", district: "대구 수성구 가선거구(예시자료)", regionIds: ["DAEGU-SUSEONG"], affiliation: "가상정당 나(예시)", term: "2026.07.01.~2030.06.30.", aliases: ["예시-대구구의원1"], homepage: "https://example.com/local1", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: true, recordKind: "sample", verificationStatus: "예시데이터", verificationSource: "", lastVerified: "2026-08-30" },
  { id: "PER-LOCAL-002", name: "예시-대구구의원2", type: "구·시·군의원", position: "구의원(예시)", district: "대구 수성구 나선거구(예시자료)", regionIds: ["DAEGU-SUSEONG"], affiliation: "가상정당 가(예시)", term: "2026.07.01.~2030.06.30.", aliases: ["예시-대구구의원2"], homepage: "https://example.com/local2", blog: "https://example.com/local2/blog", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "sample", verificationStatus: "예시데이터", verificationSource: "", lastVerified: "2026-08-30" },
  { id: "PER-LOCAL-003", name: "예시-대구군의원", type: "구·시·군의원", position: "군의원(예시)", district: "대구 군위군 비례대표(예시자료)", regionIds: ["DAEGU-GUNWI"], affiliation: "가상정당 나(예시)", term: "2026.07.01.~2030.06.30.", aliases: ["예시-대구군의원"], homepage: "https://example.com/local3", blog: "", youtube: "", facebook: "", instagram: "", threads: "", otherSns: "", active: true, focusDefault: false, recordKind: "sample", verificationStatus: "예시데이터", verificationSource: "", lastVerified: "2026-08-29" }
];
